# Generated by Django 5.2.11 on 2026-03-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurs',
            name='autor',
            field=models.ForeignKey(blank=True, help_text='Autor del recurs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='FrontEnd.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recurs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
